### ISSUE TITLE
Черный слишком черный

### ISSUE THREAD

**Issue by hovoodd** [tonsky/Universal-Layout#21]
Цвет иконки раскладки немного отличается от цвета системных иконок 😢 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23063254/55216854-f67e4180-520e-11e9-9484-343abbf1068c.gif)

**Comment by tonsky** [comment]
а я в курсе :) на самом деле макос сам как-то цвет ставит, если правильно монохромную иконку ему подсунуть. И инверсию правильно делает в dark mode.

Правда, как это сделать, я так и не понял, как ни пытался :( Кто знает — научите
