### ISSUE TITLE
Долгое нажатие капслока на русской раскладке приводит к переключению на английскую.

### ISSUE THREAD

**Issue by ayurichev** [tonsky/Universal-Layout#24]
При включенной опции `Use the Caps Lock key to switch to and from — English Universal` капслок работает не совсем корректно. 
На английской раскладке все работает нормально: короткое нажатие капса переключает на русский, длинное включает сам капс. 
На русской раскладке `Russian — Universal` короткое нажатие капса переключает язык, длинное — **одновременно** включает капс и переключает на английский. То есть нет никакой возможности включить капс на русском, потому что раскладка при этом переключается на английский. Версия Mac OS 10.14.6, других раскладок в системе нет.

**Comment by tonsky** [comment]
Печально, но не уверен что могу что-то сделать. На других не-английских раскладках как работает?

**Comment by ayurichev** [comment]
На других не-английских работает нормально, проверил три штуки. Долгое нажатие капса включает капс. А вот в системной раскладке `Russian` такая же проблема.

**Comment by ayurichev** [comment]
Еще заметил, что после длинного нажатия капс лока (при котором включается и латинская раскладка, и капс, как я писал выше) короткое нажатие действует в обратную сторону: также одновременно и отключает капс, и переключает на русскую раскладку. Выглядит как какой-то системный баг макоси, причем только для русских раскладок(

**Comment by ayurichev** [comment]
На Каталине проблема не воспроизводится, видимо, пофиксили Эпплы. Закрываю.
