### ISSUE TITLE
Раскладка для Windows

### ISSUE THREAD

**Issue by Thecentury** [tonsky/Universal-Layout#27]
Никита @tonsky, привет!

Спасибо за раскладку для Мака, давно ей пользуюсь.

Сделал начальную версию примерно такой же раскладки для Windows: https://github.com/Thecentury/Windows-Universal-Layout.

Может быть, имеет смысл добавить упоминание о ней в Readme, чтобы пользователи WIndows знали о существовании версии для них?

**Comment by tonsky** [comment]
Супер, добавил. Спасибо!
