### ISSUE TITLE
А где же одинарная кавычка?

### ISSUE THREAD

**Issue by Thecentury** [tonsky/Universal-Layout#28]
Что-то не могу найти ее, **'** ← вот эту.

**Comment by tonsky** [comment]
На тильде (на картинке не очень удачно нарисовано, сорри)

**Comment by Thecentury** [comment]
@tonsky Никита, у вас она печатается по нажатию на тильду?
У меня при нажатии без модификаторов печатается `, с шифтом появляется ~, с option — снова `.
