### ISSUE TITLE
Версия для Линуксов?

### ISSUE THREAD

**Issue by moigagoo** [tonsky/Universal-Layout#29]
Привет!

Есть шанс сделать раскладку для Линуксов? В частности, хочу в KDE использовать.

**Comment by tonsky** [comment]
Конечно, делай, с удовольствием добавлю!

**Comment by moigagoo** [comment]
FYI сделал версию для Линукса: https://github.com/moigagoo/universal-layout-linux

**Comment by tonsky** [comment]
Огонь! Добавил
