### ISSUE TITLE
Украинская раскладка

### ISSUE THREAD

**Issue by asinel** [tonsky/Universal-Layout#30]
Можно ли добавить украинскую раскладку с таким же концептом?

**Comment by tonsky** [comment]
Слушай, я в украинском совсем не разбираюсь. Предлагай, что конкретно сделать?

**Comment by asinel** [comment]
Тоже самое что и с русской, только:
- вместо "ы" - "і", 
- там же через Альт - "ї" (в оригинале она там где твердый знак, но думаю концептуально правильно через Альт). 
- Вместо э - є
- Ну и апостроф куда-то засунуть, мне сложно сказать куда... В оригинальной он там где "є" через шифт, т.к. ни одно слово с этой буквы не начинается и она не нужна большая, мб можно там и оставить
- Ну и на месте знака рубля - знак гривны.

Это бы очень помогло, а то сейчас неудобно переключаться (оригинальные русская и укр. раскладка намного сильнее между собой дружат), спасибо

**Comment by tonsky** [comment]
Попробуй?

**Comment by asinel** [comment]
@tonsky Всё отлично работает, спасибо)

**Comment by samokisha** [comment]
Привет.
В украинском языке нет 'ё' и 'ъ'.
Если я правильно понимаю концепцию, их можно убрать вовсе.

**Comment by tonsky** [comment]
@samokisha спасибо, пофиксил!
