### ISSUE TITLE
Невозможно удалить английскую раскладку по умолчанию

### ISSUE THREAD

**Issue by wizzytod** [tonsky/Universal-Layout#4]
MacOS 10.14 (Mojave)

<img width="780" alt="screenshot 2018-10-29 at 10 14 04" src="https://user-images.githubusercontent.com/9740575/47634723-93a35400-db63-11e8-8376-6a8ef539e614.png">

**Comment by freetonik** [comment]
Добавьте японскую, потом удалите английскую, потом удалите японскуюю

**Comment by tonsky** [comment]
Я кстати оставляю, потому что некоторые сайты когда просят ввести число видимо реализуют какой-то нестандартный собственный ввод, и цифры с шифтом у них не работают

**Comment by wizzytod** [comment]
А как переключаешься между раскладками тогда? Если две раскладки, то отлично работает Cmd+Space?

**Comment by tonsky** [comment]
Select the previous input source будет тебя гонять между двумя последними, сколько бы их не было установлено. Я так довольно долго сидел с раскладкой Бирмана. Сейчас вообще настроил hammerspoon чтобы одна кнопка безусловно включала английскую, а вторая — безусловно русскую

**Comment by wizzytod** [comment]
Спасибо, работает!

**Comment by freetonik** [comment]
Или вот если не хочется возиться с hammerspoon'ом http://bluezbox.com/mlswitcher2.html
