### ISSUE TITLE
Добавить кириллические І, Ї, Є, Ґ на второй уровень (вместе с Ё)

### ISSUE THREAD

**Issue by rozhok** [tonsky/Universal-Layout#7]
Это позволит держать одну раскладку для украинцев/беларусов/других славян, которые пользуются кириллицей. В данный момент я использую модифицированную раскладку Бирмана, которая как раз совмещает все эти символы—очень удобно.

**Comment by 5311O** [comment]
+1

**Comment by tonsky** [comment]
Є є тоже?
