### ISSUE TITLE
Переключение по Caps Lock

### ISSUE THREAD

**Issue by 5311O** [tonsky/Universal-Layout#8]
Switching by Caps Lock is not working when having both English Universal and Russian Universal added. If remove English Universal and have following ones Caps Lock switcher works fine:
ABC
Russian Mac
Russian Universal

**Comment by tonsky** [comment]
пиши уже по-русски :) как настроено переключение? очень сомнительно что раскладка может на него влиять

**Comment by 5311O** [comment]
Совершенно стандартная макосная птичка переключения по капсу которая из коробки - почему-то если оставлять только твои раскладки, то эта птичка в сеттингах пропадает, не знаю с чем связано, может какие-то байндинги на капс повешены в самой раскладке каким-то образом

**Comment by tonsky** [comment]
скриншот птички? мне надо воспроизвести

**Comment by 5311O** [comment]
Средняя птичка use caps lock blah blah
<img width="620" alt="screen shot 2018-10-29 at 8 07 30 pm" src="https://user-images.githubusercontent.com/1651240/47670630-57e5aa00-dbb6-11e8-9bf1-45ee84859845.png">

**Comment by alex-mos** [comment]
Кстати, про Caps Lock — он совсем перестал работать. А было бы удобно включать его, когда нужно работать с цифрами.
